<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('referrals', function (Blueprint $table) {
            $table->id();
            $table->foreignId('referrer_id')->constrained('users')->onDelete('cascade');
            $table->foreignId('referred_user_id')->constrained('users')->onDelete('cascade');
            $table->decimal('profit_generated', 15, 2)->default(0.00)->comment('Admin profit generated by referred user');
            $table->enum('status', ['Locked', 'Unlocked'])->default('Locked');
            $table->unsignedInteger('bonus_points')->default(500)->comment('Points to be unlocked when threshold met');
            $table->decimal('unlock_threshold', 10, 2)->default(10.00)->comment('BDT profit threshold to unlock bonus');
            $table->timestamp('unlocked_at')->nullable();
            $table->timestamps();

            $table->unique('referred_user_id'); // One referral per user
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('referrals');
    }
};
